### ISSUE TITLE
[BUG] Issue with spawn timeouts after local pip installation of python packages

### ISSUE THREAD

**Issue by brantr** [rubin-dp0/Support#16]
After pip installing python 3.8 packages into .local, I could not spawn further instances without clearing .local first.

**Comment by frossie** [comment]
[I asked the user to file a stub ticket during in-person troubleshooting, blame me]

We support users being able to add additional packages to their notebook environment. In what is generally a rare case, the user can do something that prevents their notebook server from starting (a situation from which you can immediately recover my ticket the "Clear my .local" option when launching a new server. 

We are investigating whether recent changes on how the Science Pipelines python environment is managed have made this more likely to be a problem, and also what specific package caused the issue @brantr encountered.

**Comment by athornton** [comment]
Trying "conda install tensorflow":

[athornton@nb-athornton ~]$ conda install tensorflow
Collecting package metadata (current_repodata.json): done
Solving environment: \ 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::dask-kubernetes==0.11.0=py_0
  - conda-forge/noarch::ipympl==0.8.0=pyhd8ed1ab_0
  - conda-forge/noarch::jupyterlab_iframe==0.2.3=pyhd8ed1ab_0
  - conda-forge/noarch::dask-labextension==4.0.1=pyhd8ed1ab_0
  - conda-forge/noarch::pywwt==0.12.0=pyhd8ed1ab_0
  - conda-forge/linux-64::nbconvert==6.1.0=py38h578d9bd_1
  - conda-forge/noarch::ipydatawidgets==4.2.0=pyhd3deb0d_0
  - conda-forge/noarch::ipyvolume==0.6.0a8=pyhd8ed1ab_0
  - conda-forge/noarch::ipywidgets==7.6.5=pyhd8ed1ab_0
  - conda-forge/noarch::ipyevents==2.0.1=pyhd8ed1ab_0
  - conda-forge/noarch::nbval==0.9.6=pyh9f0ad1d_0
  - conda-forge/noarch::nbclient==0.5.4=pyhd8ed1ab_0
  - conda-forge/noarch::ipywebrtc==0.6.0=pyhd8ed1ab_0
  - conda-forge/linux-64::jupyterhub-base==1.4.2=py38h578d9bd_0
  - conda-forge/noarch::nbdime==3.1.0=pyhd8ed1ab_0
  - conda-forge/linux-64::widgetsnbextension==3.5.1=py38h578d9bd_4
  - conda-forge/linux-64::ipykernel==5.5.5=py38hd0cf306_0
  - conda-forge/noarch::bqplot==0.12.30=pyhd8ed1ab_0
  - conda-forge/noarch::astrowidgets==0.2.0=pyhd8ed1ab_0
  - conda-forge/noarch::sidecar==0.4.0=pyh9f0ad1d_0
  - conda-forge/noarch::jupyterlab==2.3.2=pyhd8ed1ab_0
  - conda-forge/noarch::jupyter_server==1.11.0=pyhd8ed1ab_0
  - conda-forge/noarch::jupyter-server-proxy==3.1.0=pyhd8ed1ab_0
  - conda-forge/noarch::paramnb==2.0.4=py_0
  - conda-forge/linux-64::jupyterhub==1.4.2=py38h578d9bd_0
  - conda-forge/noarch::jupyter-server-mathjax==0.2.3=pyhd8ed1ab_0
  - conda-forge/noarch::notebook==6.4.4=pyha770c72_0
  - conda-forge/noarch::dask_labextension==4.0.1=hd8ed1ab_0
  - conda-forge/noarch::papermill==2.3.3=pyhd8ed1ab_0
  - conda-forge/noarch::pythreejs==2.3.0=pyhd8ed1ab_0
  - conda-forge/noarch::jupyterlab_server==1.2.0=py_0
  - conda-forge/noarch::jupyter_telemetry==0.1.0=pyhd8ed1ab_1
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::dask-kubernetes==0.11.0=py_0
  - conda-forge/noarch::ipympl==0.8.0=pyhd8ed1ab_0
  - conda-forge/noarch::jupyterlab_iframe==0.2.3=pyhd8ed1ab_0
  - conda-forge/noarch::dask-labextension==4.0.1=pyhd8ed1ab_0
  - conda-forge/noarch::pywwt==0.12.0=pyhd8ed1ab_0
  - conda-forge/linux-64::nbconvert==6.1.0=py38h578d9bd_1
  - conda-forge/noarch::ipydatawidgets==4.2.0=pyhd3deb0d_0
  - conda-forge/noarch::ipyvolume==0.6.0a8=pyhd8ed1ab_0
  - conda-forge/noarch::ipywidgets==7.6.5=pyhd8ed1ab_0
  - conda-forge/noarch::ipyevents==2.0.1=pyhd8ed1ab_0
  - conda-forge/noarch::nbval==0.9.6=pyh9f0ad1d_0
  - conda-forge/noarch::nbclient==0.5.4=pyhd8ed1ab_0
  - conda-forge/noarch::ipywebrtc==0.6.0=pyhd8ed1ab_0
  - conda-forge/linux-64::jupyterhub-base==1.4.2=py38h578d9bd_0
  - conda-forge/noarch::nbdime==3.1.0=pyhd8ed1ab_0
  - conda-forge/linux-64::widgetsnbextension==3.5.1=py38h578d9bd_4
  - conda-forge/linux-64::ipykernel==5.5.5=py38hd0cf306_0
  - conda-forge/noarch::bqplot==0.12.30=pyhd8ed1ab_0
  - conda-forge/noarch::astrowidgets==0.2.0=pyhd8ed1ab_0
  - conda-forge/noarch::sidecar==0.4.0=pyh9f0ad1d_0
  - conda-forge/noarch::jupyterlab==2.3.2=pyhd8ed1ab_0
  - conda-forge/noarch::jupyter_server==1.11.0=pyhd8ed1ab_0
  - conda-forge/noarch::jupyter-server-proxy==3.1.0=pyhd8ed1ab_0
  - conda-forge/noarch::paramnb==2.0.4=py_0
  - conda-forge/linux-64::jupyterhub==1.4.2=py38h578d9bd_0
  - conda-forge/noarch::jupyter-server-mathjax==0.2.3=pyhd8ed1ab_0
  - conda-forge/noarch::notebook==6.4.4=pyha770c72_0
  - conda-forge/noarch::dask_labextension==4.0.1=hd8ed1ab_0
  - conda-forge/noarch::papermill==2.3.3=pyhd8ed1ab_0
  - conda-forge/noarch::pythreejs==2.3.0=pyhd8ed1ab_0
  - conda-forge/noarch::jupyterlab_server==1.2.0=py_0
  - conda-forge/noarch::jupyter_telemetry==0.1.0=pyhd8ed1ab_1
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: done

## Package Plan ##

  environment location: /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0

  added / updated specs:
    - tensorflow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    abseil-cpp-20200923.3      |       h9c3ff4c_0         955 KB  conda-forge
    absl-py-0.13.0             |     pyhd8ed1ab_0          97 KB  conda-forge
    arrow-cpp-3.0.0            |py38h140c071_10_cpu        21.6 MB  conda-forge
    astor-0.8.1                |     pyh9f0ad1d_0          25 KB  conda-forge
    astunparse-1.6.3           |     pyhd8ed1ab_0          15 KB  conda-forge
    aws-c-cal-0.4.5            |       h5ca8eb3_9          35 KB  conda-forge
    aws-c-common-0.5.8         |       h7f98852_0         166 KB  conda-forge
    aws-c-event-stream-0.2.7   |       h832d4c5_2          47 KB  conda-forge
    aws-c-io-0.9.4             |       hfee9f7d_5         120 KB  conda-forge
    aws-checksums-0.1.11       |       hdc257ea_4          50 KB  conda-forge
    aws-sdk-cpp-1.8.151        |       h973185b_2         4.5 MB  conda-forge
    conda-4.10.3               |   py38h578d9bd_1         3.1 MB  conda-forge
    gast-0.3.3                 |             py_0          12 KB  conda-forge
    glog-0.4.0                 |       h49b9bf7_3         104 KB  conda-forge
    google-auth-1.35.0         |     pyh6c4a22f_0          81 KB  conda-forge
    google-pasta-0.2.0         |     pyh8c360ce_0          42 KB  conda-forge
    grpc-cpp-1.36.4            |       hf89561c_1         3.4 MB  conda-forge
    grpcio-1.36.1              |   py38hdd6454d_0         2.1 MB  conda-forge
    h5py-2.10.0                |nompi_py38h9915d05_106         1.1 MB  conda-forge
    jupyter_client-7.0.3       |     pyhd8ed1ab_0          86 KB  conda-forge
    keras-preprocessing-1.1.2  |     pyhd8ed1ab_0          34 KB  conda-forge
    libprotobuf-3.15.8         |       h780b84a_1         2.5 MB  conda-forge
    opt_einsum-3.3.0           |     pyhd8ed1ab_1          53 KB  conda-forge
    orc-1.6.7                  |       heec2584_1         750 KB  conda-forge
    protobuf-3.15.8            |   py38h709712a_0         341 KB  conda-forge
    pyarrow-3.0.0              |py38hc9229eb_10_cpu         2.5 MB  conda-forge
    python-flatbuffers-1.12    |     pyhd8ed1ab_1          19 KB  conda-forge
    python-kubernetes-18.20.0  |     pyhd8ed1ab_0         473 KB  conda-forge
    ruamel.yaml-0.17.16        |   py38h497a2fe_0         171 KB  conda-forge
    s2n-1.0.5                  |       h9b69904_0         394 KB  conda-forge
    tensorboard-2.4.1          |     pyhd8ed1ab_1         8.8 MB  conda-forge
    tensorboard-plugin-wit-1.8.0|     pyh44b312d_0         670 KB  conda-forge
    tensorflow-2.4.0           |   py38h578d9bd_0          25 KB  conda-forge
    tensorflow-base-2.4.0      |   py38h01d9eeb_0        93.1 MB  conda-forge
    tensorflow-estimator-2.4.0 |     pyh9656e83_0         289 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       147.7 MB

The following NEW packages will be INSTALLED:

  absl-py            conda-forge/noarch::absl-py-0.13.0-pyhd8ed1ab_0
  astor              conda-forge/noarch::astor-0.8.1-pyh9f0ad1d_0
  astunparse         conda-forge/noarch::astunparse-1.6.3-pyhd8ed1ab_0
  gast               conda-forge/noarch::gast-0.3.3-py_0
  google-pasta       conda-forge/noarch::google-pasta-0.2.0-pyh8c360ce_0
  grpcio             conda-forge/linux-64::grpcio-1.36.1-py38hdd6454d_0
  jupyter_client     conda-forge/noarch::jupyter_client-7.0.3-pyhd8ed1ab_0
  keras-preprocessi~ conda-forge/noarch::keras-preprocessing-1.1.2-pyhd8ed1ab_0
  opt_einsum         conda-forge/noarch::opt_einsum-3.3.0-pyhd8ed1ab_1
  protobuf           conda-forge/linux-64::protobuf-3.15.8-py38h709712a_0
  python-flatbuffers conda-forge/noarch::python-flatbuffers-1.12-pyhd8ed1ab_1
  python-kubernetes  conda-forge/noarch::python-kubernetes-18.20.0-pyhd8ed1ab_0
  ruamel.yaml        conda-forge/linux-64::ruamel.yaml-0.17.16-py38h497a2fe_0
  tensorboard        conda-forge/noarch::tensorboard-2.4.1-pyhd8ed1ab_1
  tensorboard-plugi~ conda-forge/noarch::tensorboard-plugin-wit-1.8.0-pyh44b312d_0
  tensorflow         conda-forge/linux-64::tensorflow-2.4.0-py38h578d9bd_0
  tensorflow-base    conda-forge/linux-64::tensorflow-base-2.4.0-py38h01d9eeb_0
  tensorflow-estima~ conda-forge/noarch::tensorflow-estimator-2.4.0-pyh9656e83_0

The following packages will be UPDATED:

  conda                               4.10.3-py38h578d9bd_0 --> 4.10.3-py38h578d9bd_1

The following packages will be DOWNGRADED:

  abseil-cpp                          20210324.1-h9c3ff4c_0 --> 20200923.3-h9c3ff4c_0
  arrow-cpp                        4.0.0-py38h8e6f228_3_cpu --> 3.0.0-py38h140c071_10_cpu
  aws-c-cal                               0.5.11-h95a6274_0 --> 0.4.5-h5ca8eb3_9
  aws-c-common                             0.6.2-h7f98852_0 --> 0.5.8-h7f98852_0
  aws-c-event-stream                      0.2.7-h3541f99_13 --> 0.2.7-h832d4c5_2
  aws-c-io                                0.10.5-hfb6a706_0 --> 0.9.4-hfee9f7d_5
  aws-checksums                           0.1.11-ha31a3da_7 --> 0.1.11-hdc257ea_4
  aws-sdk-cpp                            1.8.186-hb4091e7_3 --> 1.8.151-h973185b_2
  glog                                     0.5.0-h48cff8f_0 --> 0.4.0-h49b9bf7_3
  google-auth                            2.0.2-pyh6c4a22f_0 --> 1.35.0-pyh6c4a22f_0
  grpc-cpp                                1.37.1-h2519f57_2 --> 1.36.4-hf89561c_1
  h5py                         3.3.0-nompi_py38h9915d05_100 --> 2.10.0-nompi_py38h9915d05_106
  libprotobuf                             3.16.0-h780b84a_0 --> 3.15.8-h780b84a_1
  orc                                      1.6.7-h89a63ab_2 --> 1.6.7-heec2584_1
  pyarrow                          4.0.0-py38hc9229eb_3_cpu --> 3.0.0-py38hc9229eb_10_cpu
  s2n                                     1.0.10-h9b69904_0 --> 1.0.5-h9b69904_0

**Comment by athornton** [comment]
Proceed ([y]/n)? y


Downloading and Extracting Packages
aws-c-common-0.5.8   | 166 KB    | ############################################################################################### | 100% 
grpcio-1.36.1        | 2.1 MB    | ############################################################################################### | 100% 
ruamel.yaml-0.17.16  | 171 KB    | ############################################################################################### | 100% 
aws-c-event-stream-0 | 47 KB     | ############################################################################################### | 100% 
aws-sdk-cpp-1.8.151  | 4.5 MB    | ############################################################################################### | 100% 
tensorflow-base-2.4. | 93.1 MB   | ############################################################################################### | 100% 
aws-c-io-0.9.4       | 120 KB    | ############################################################################################### | 100% 
jupyter_client-7.0.3 | 86 KB     | ############################################################################################### | 100% 
orc-1.6.7            | 750 KB    | ############################################################################################### | 100% 
libprotobuf-3.15.8   | 2.5 MB    | ############################################################################################### | 100% 
s2n-1.0.5            | 394 KB    | ############################################################################################### | 100% 
absl-py-0.13.0       | 97 KB     | ############################################################################################### | 100% 
h5py-2.10.0          | 1.1 MB    | ############################################################################################### | 100% 
protobuf-3.15.8      | 341 KB    | ############################################################################################### | 100% 
grpc-cpp-1.36.4      | 3.4 MB    | ############################################################################################### | 100% 
aws-checksums-0.1.11 | 50 KB     | ############################################################################################### | 100% 
opt_einsum-3.3.0     | 53 KB     | ############################################################################################### | 100% 
tensorflow-2.4.0     | 25 KB     | ############################################################################################### | 100% 
python-flatbuffers-1 | 19 KB     | ############################################################################################### | 100% 
python-kubernetes-18 | 473 KB    | ############################################################################################### | 100% 
google-pasta-0.2.0   | 42 KB     | ############################################################################################### | 100% 
astor-0.8.1          | 25 KB     | ############################################################################################### | 100% 
conda-4.10.3         | 3.1 MB    | ############################################################################################### | 100% 
pyarrow-3.0.0        | 2.5 MB    | ############################################################################################### | 100% 
tensorboard-plugin-w | 670 KB    | ############################################################################################### | 100% 
tensorboard-2.4.1    | 8.8 MB    | ############################################################################################### | 100% 
arrow-cpp-3.0.0      | 21.6 MB   | ############################################################################################### | 100% 
aws-c-cal-0.4.5      | 35 KB     | ############################################################################################### | 100% 
tensorflow-estimator | 289 KB    | ############################################################################################### | 100% 
keras-preprocessing- | 34 KB     | ############################################################################################### | 100% 
gast-0.3.3           | 12 KB     | ############################################################################################### | 100% 
glog-0.4.0           | 104 KB    | ############################################################################################### | 100% 
google-auth-1.35.0   | 81 KB     | ############################################################################################### | 100% 
astunparse-1.6.3     | 15 KB     | ############################################################################################### | 100% 
abseil-cpp-20200923. | 955 KB    | ############################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: failed

EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0
  uid: 2453165
  gid: 2453165

**Comment by athornton** [comment]
Interesting.  I would have expected Conda to silently try doing a local install as pip does.

OK, now I'll try a ``pip install tensorflow``

**Comment by athornton** [comment]
[athornton@nb-athornton ~]$ pip install tensorflow
Defaulting to user installation because normal site-packages is not writeable
Collecting tensorflow
  Downloading tensorflow-2.6.0-cp38-cp38-manylinux2010_x86_64.whl (458.4 MB)
     |████████████████████████████████| 458.4 MB 34 kB/s 
Collecting tensorboard~=2.6
  Downloading tensorboard-2.6.0-py3-none-any.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 97.3 MB/s 
Collecting tensorflow-estimator~=2.6
  Downloading tensorflow_estimator-2.6.0-py2.py3-none-any.whl (462 kB)
     |████████████████████████████████| 462 kB 87.4 MB/s 
Collecting opt-einsum~=3.3.0
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 1.9 MB/s 
Collecting flatbuffers~=1.12.0
  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting keras-preprocessing~=1.1.2
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 471 kB/s 
Collecting grpcio<2.0,>=1.37.0
  Downloading grpcio-1.40.0-cp38-cp38-manylinux2014_x86_64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 66.1 MB/s 
Requirement already satisfied: wrapt~=1.12.1 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from tensorflow) (1.12.1)
Collecting protobuf>=3.9.2
  Downloading protobuf-3.18.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 74.9 MB/s 
Collecting numpy~=1.19.2
  Downloading numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
     |████████████████████████████████| 14.9 MB 59.5 MB/s 
Collecting google-pasta~=0.2
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 2.2 MB/s 
Collecting six~=1.15.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: wheel~=0.35 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from tensorflow) (0.37.0)
Requirement already satisfied: termcolor~=1.1.0 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from tensorflow) (1.1.0)
Collecting typing-extensions~=3.7.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting keras~=2.6
  Downloading keras-2.6.0-py2.py3-none-any.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 81.8 MB/s 
Collecting absl-py~=0.10
  Downloading absl_py-0.14.0-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 80.9 MB/s 
Collecting h5py~=3.1.0
  Downloading h5py-3.1.0-cp38-cp38-manylinux1_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 65.9 MB/s 
Collecting clang~=5.0
  Downloading clang-5.0.tar.gz (30 kB)
Collecting gast==0.4.0
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting astunparse~=1.6.3
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: markdown>=2.6.8 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow) (3.3.4)
Requirement already satisfied: setuptools>=41.0.0 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow) (58.0.3)
Requirement already satisfied: werkzeug>=0.11.15 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow) (2.0.1)
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
     |████████████████████████████████| 781 kB 85.9 MB/s 
Requirement already satisfied: requests<3,>=2.21.0 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow) (2.26.0)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
     |████████████████████████████████| 4.9 MB 87.4 MB/s 
Collecting google-auth<2,>=1.6.3
  Downloading google_auth-1.35.0-py2.py3-none-any.whl (152 kB)
     |████████████████████████████████| 152 kB 96.0 MB/s 
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow) (0.4.6)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.6->tensorflow) (0.2.7)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.6->tensorflow) (4.2.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.6->tensorflow) (4.7.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard~=2.6->tensorflow) (0.4.8)
Requirement already satisfied: idna<4,>=2.5 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (2021.5.30)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (2.0.0)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-0.7.0/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow) (3.1.1)
Building wheels for collected packages: clang
  Building wheel for clang (setup.py) ... done
  Created wheel for clang: filename=clang-5.0-py3-none-any.whl size=30692 sha256=830db0c15eb9e5750199bf72d7405dcc51f89dfc3ac7972a9ddb2e0d6e17391d
  Stored in directory: /home/athornton/.cache/pip/wheels/f1/60/77/22b9b5887bd47801796a856f47650d9789c74dc3161a26d608
Successfully built clang
Installing collected packages: six, google-auth, tensorboard-plugin-wit, tensorboard-data-server, protobuf, numpy, grpcio, absl-py, typing-extensions, tensorflow-estimator, tensorboard, opt-einsum, keras-preprocessing, keras, h5py, google-pasta, gast, flatbuffers, clang, astunparse, tensorflow
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
piff 1.0.0 requires galsim, which is not installed.
black 21.9b0 requires typing-extensions>=3.10.0.0, but you have typing-extensions 3.7.4.3 which is incompatible.
Successfully installed absl-py-0.14.0 astunparse-1.6.3 clang-5.0 flatbuffers-1.12 gast-0.4.0 google-auth-1.35.0 google-pasta-0.2.0 grpcio-1.40.0 h5py-3.1.0 keras-2.6.0 keras-preprocessing-1.1.2 numpy-1.19.5 opt-einsum-3.3.0 protobuf-3.18.0 six-1.15.0 tensorboard-2.6.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 tensorflow-2.6.0 tensorflow-estimator-2.6.0 typing-extensions-3.7.4.3

**Comment by athornton** [comment]
Now I"m going to see if I get stuck on respawn.

**Comment by athornton** [comment]
Working to reproduce the error.

**Comment by athornton** [comment]
Using recommended (currently weekly 33), I was able to do a `pip install tensorflow` and spawn a new container, in which I can run `import tensorflow` inside a notebook without an issue.

That said, it is certainly the case, particularly as the image you're using gets older relative to the current state of the world, that if you install something into the system context (which is what pip install --user effectively does, without a virtualenv), that there are going to be incompatible versions of things.

The much safer way to go about this is to create a virtualenv, and then create a kernel for that virtualenv.  To use tensorflow as an example:

```
python3 -m venv ~/Venvs/TF
source ~/Venvs/TF/bin/activate
pip install jupyter tensorflow
ipython kernel install --name TF --user
```
(You need to install `jupyter` to be able to create a kernel from your new virtualenv.)

Then you have to shut down your pod (from the bottom of the File menu) and respawn.

Upon respawn, your new kernel will be available for use within Jupyterlab notebooks and consoles.  If you activate that virtualenv, you can pip install whatever you like into it.

A similar process works for conda, with the caveat that since the root filesystem is not writeable, if you do a `conda env clone` and start with the lsst-scipipe-env environment as your clone source, it's going to take up a _lot_ of space in your home directory, since what you're getting is a copy of the entire DM stack.

**Comment by brantr** [comment]
Hi @athornton, thanks very much! I had tried most of your solution but was apparently missing the last step. I can now access my software stack within a notebook after pip installing the required packages and activating the virtual environment from within the notebook. I'll mark this as closed, thanks again.
