### ISSUE TITLE
[SUGGESTION] Install AAS WorldWide Telescope JupyterLab components

### ISSUE THREAD

**Issue by pkgw** [rubin-dp0/Support#19]
**Is your feature request related to a problem? Please describe.**
I want to explore whether the [AAS WorldWide Telescope][wwt] (WWT) software package can deliver a compelling solution for exploratory visualization of Rubin imagery on the RSP.

[wwt]: https://worldwidetelescope.org/home/

**Describe the solution you'd like**
In order to test out the WWT visualization framework for this use case, a few software components need to be added to the RSP JupyterLab stack (see below).

**Describe alternatives you've considered**
Most of the WWT components can installed at the user level if needed, but there are a couple of server extensions required in order to pass data from the kernel backend(s) to the browser frontend. I don't believe that those are user-installable with the RSP setup, although I'm not 100% sure about that.

**Additional context**
The key server extensions are:

- [pywwt](https://pypi.org/project/pywwt/)
- [wwt_kernel_data_relay](https://pypi.org/project/wwt-kernel-data-relay/)

The ideal setup would also include the WWT JupyterLab extension, installable either as:

- [@wwtelescope/jupyterlab](https://www.npmjs.com/package/@wwtelescope/jupyterlab) "source" form
- [wwt_jupyterlab_extension](https://pypi.org/project/wwt-jupyterlab-extension/) "prebuilt" form

There are also kernel-side Python packages to complete the framework (most importantly pywwt) but those can be user-installed if needed.

**Comment by pkgw** [comment]
Hi — is there any extra information that I can provide that would help move this ticket forward? Thanks!

**Comment by frossie** [comment]
Apologies for the delay. The short answer is that we are not prepared to support the WWT on the Rubin Science Platform at this time. We have removed it from our notebook aspect interface. 
The long answer is that there are a lot of challenges in supporting a compute environment for thousands of users, and testing that everything works (and stays working) is an effort-consuming process. We therefore look for "common denominator" packages that are requested by a sizeable fraction of the community as well as our own internal science users, so that we can be certain that they are extensively used and that they have active users as internal champions. At this (pre-operations) stage of the project we have not been able to find any compelling interest in using WWT in the RSP nor any current WWT users among our product owners. Moreover, graphical user interfaces are a worst-case scenario, as they are not tractable to our current automated testing and have an even higher bar for being made available than numeric packages. 
In the long run, during Rubin Operations we will develop a process for adding capabilities to the RSP in consultation with our User Committee. I anticipate that at that time, we might be able to add capabilities without internal project advocates under circumstances where third-party support can be provided by another institution. That will be a good time to revisit the WWT issue. Sorry to be the bearer of bad news.

**Comment by MelissaGraham** [comment]
Congratulations and best wishes @pkgw! 

Rubin Observatory will have a booth in the AAS 240 Exhibit Hall, and I'll be there a lot of the time. Looking forward to chatting.
