### ISSUE TITLE
[BUG]  Problem to start the portal and notebook aspects of the RSP

### ISSUE THREAD

**Issue by mardom** [rubin-dp0/Support#4]
**Describe the bug**
Error trying to start the portal and notebook aspects: 

**To Reproduce**
1. Go to https://data.lsst.cloud/ and login
2. Click on https://data.lsst.cloud/portal/app/ or https://data.lsst.cloud/nb
3. 403 Forbidden nginx

**Expected behavior**
could start working with example notebooks and DC2 tables

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Linux Pop!_OS 20.10
 - Browser Chrome
 - Version 91.0

**Additional context**
Could log without problem, Github account linked and accepted @DP0 organization in the first login.
cleaned local cache and generate new security token, will try the API next
Thank you in advance, m.

**Comment by MelissaGraham** [comment]
Hi Mariano,

My apologies, this issue is my fault, because I had not yet sent you the invitation to join this GitHub Org and its Delegates team. I have just done this. Please accept the invitation and then try again. 

Note that since you tried to access the RSP before accepting an invite to the rubin-dp0 you will have an incorrectly scoped token for RSP access, and will have to follow these instructions to recover:

https://github.com/rubin-dp0/Support/issues/1#issuecomment-871904198

Thank you for doing the action items and filling out the Delegates Authorization Form and my apologies again for this issue!

Please report back to confirm once you can log in to the RSP's Notebook and Portal Aspects, and then we'll close this issue.

**Comment by frossie** [comment]
Hello @mardom - have you had a chance to follow Melissa's suggestion above?

**Comment by frossie** [comment]
@mardom you should now be able to resolve the situation by 

1. logging out (if you are still logged in)
2. logging in
3. logging out

After which you should be fine.

**Comment by mardom** [comment]
Hi @frossie and  @MelissaGraham 
     Sorry for the delay in answer to you.  Yes, the issue was resolved, and I could start using the RSP. Thank you! All the best, m.
