### ISSUE TITLE
[BUG] authentication error

### ISSUE THREAD

**Issue by RAnjosUFBA** [rubin-dp0/Support#55]
I am having authentication error. I think because I signed in with my ORCID and then made a new request with my corporate university email and now there are 2 different names associated with my account. What do I do?

"Authentication error

Authentication failed with the following error:

Error: Authentication provider failed: OpenID Connect token verification failed: Invalid username claim in token: ['rafaela-anjos', 'rafaela-anjos13']

To report problems or ask for help, please open an issue in the [GitHub rubin-dp0/Support project](https://github.com/rubin-dp0/Support/issues)."

**Comment by jeffcarlin** [comment]
Hello Rafaela - It is perfectly fine for you to have two different identity providers for authentication, but I do indeed see two usernames in the system, so that may be an issue. Have you tried logging in with both your ORCID and your UFBA credentials? Both should work, unless there is some other problem.

If you are unable to log in with either ORCID or UFBA, then we will need to dig deeper.

**Comment by RAnjosUFBA** [comment]
I can't connect using either orcid or UFBA. Both show the same authentication error.

**Comment by jeffcarlin** [comment]
OK, that's something we will have to look into in more detail (probably on Monday).

**Comment by RAnjosUFBA** [comment]
Ok, during this weekend I will try to connect to see if it is not a momentary error. Any news notice here. Thank you very much, see you soon.

**Comment by frossie** [comment]
There is an actual issue with this user's token. Not sure why. It will get looked at Monday.

**Comment by rra** [comment]
Hi Rafaela,

I've deleted your second username (rafaela-anjos13) so now you have only one username again. This should fix the problem. Try again when you have a chance and let us know if it's still not working. Both of your associated identities should still work for login purposes.

This is a bug we've been dealing with for some time, and unfortunately the software fix that's supposed to prevent this from happening hasn't been deployed yet. To check, to be sure I understand the nature of the problem, did you get prompted for a username again when you added your university email identity? And how did you add that identity? Was that through the "Link another account" menu item, or some other way?

**Comment by RAnjosUFBA** [comment]
Now it worked smoothly logging in using my orcid. Yes, when I went to link my university email it asked me for a new name and I just added the "13" at the end. Now it works normally, thank you!

**Comment by rra** [comment]
Okay, thank you! That's very helpful and may explain why we keep having this problem. It shouldn't have done that; it should have used your existing username. We'll follow up with the CILogon folks about this problem. Sorry for the hassle!

I'll close this out since you say it's working but let us know if you have any more problems.
