### ISSUE TITLE
[BUG] RSP Logon Errors 

### ISSUE THREAD

**Issue by yksheen** [rubin-dp0/Support#62]
**Describe the bug**
I cannot login to RSP and every time face different types of error messages(endpoint, permission, redirects). 
I am on the DRH list and my e-mail address is already verified by the system. 

**To Reproduce**
0. Remove all the cookies from Chrome settings 
1. Go to 'https://data.lsst.cloud'
2. Click on 'Log in'
3. Select an Identity Provider and Log On 
4. Login to CILogon using my username and password 
5. User Information, click on 'Yes, continue' 
6. 'Consent to Attribute Release' appears again and Select an Identity Provider to Log On 
7. This time, I have got "CILogon OIDC Authorization Endpoint' (please refer to the first screen shot below)
8. Previously, I saw 'Self Signup With Approval' page with error messages (please refer to the second screen shot below) 
9. In other times, it used to end up with a message, "ERR_TOO_MANY_REDIRECTS", since yesterday. 

**Expected behavior**
I have no idea because I haven't succeeded to log in to the RSP. I would expect being followed by next step after e-mail verification.

**Screenshots**
<img width="1433" alt="스크린샷 2024-03-06 오전 11 19 54" src="https://github.com/rubin-dp0/Support/assets/125853846/208e113a-0cb1-4398-b672-c86c6fba9513">
<img width="1433" alt="스크린샷 2024-03-06 오전 11 03 24" src="https://github.com/rubin-dp0/Support/assets/125853846/01fa282e-bf13-4b82-8b49-25e56942c55d">

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.0
 - Browser: Chrome
 - Version: 122.0.6261.112

**Comment by MelissaGraham** [comment]
A bit of extra background to explain why Yun-Kyeong says "this time" and "previously" -- I tried to help but got stuck. 

When the login errors initially began, my best guess was that the email verification step looks like it only half-worked, and I suspected that was why the next step ("petition" stage where we verify data rights, which Yun-Kyeong does have as a named member of the Korean in-kind team) was not prompted. I went in and under "person attributes" I changed their "status" from "pending confirmation" to "active". But that did not help.

If there's a way to finalize Yun-Kyeong's account without expunging and starting over, that would be good, but as I understand it since they haven't yet had a successful login, expunging is an option.

**Comment by frossie** [comment]
Right, to Melissa's comment, I don't think there's anything one can do on the CILogon  UI to "force" the user confirmation (I know it looks like what you did should work but unfortunately it does not - I also have been caught out by this). I'd say expunge and start again - and user should check Spam to make sure that's not where the confirmation email is ending up. 

The too many redirects issue  - try clearing cookies from cilogon.org and data.lsst.cloud or using private browsing mode or using a different browser.

**Comment by yksheen** [comment]
I tried again to get an account on the RSP from the first step and it is approved! Now I can access RSP Portal and Notebooks. Thanks @MelissaGraham and @frossie for your help!

**Comment by MelissaGraham** [comment]
Great news @yksheen thanks for confirming!
