### ISSUE TITLE
[Authentication Error] 

### ISSUE THREAD

**Issue by ZhuofuLi** [rubin-dp0/Support#63]
<img width="1476" alt="Screenshot 2024-04-17 at 2 03 35 PM" src="https://github.com/rubin-dp0/Support/assets/107944375/86e9bc51-76fc-45bf-bc77-293d15bcaf42">

I can't log into the Rubin Science Platform. 

**To Reproduce**
1. Go to https://data.lsst.cloud/
2. Click on 'Log in'
3. Choose 'Github'
4. Click on 'Log on'
5. See error (see the attached screenshot)

**Expected behavior**
I want to log in.

**URL**
https://data.lsst.cloud/

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Version 123.0.6312.124

**Comment by rra** [comment]
It looks like your account fell victim to a bug in our identity management system that resulted in you having two different usernames assigned at the same time, which breaks all sorts of things. It seems to have been that way since September of 2023. We have a fix in place for this bug now, so hopefully this problem shouldn't happen again.

You currently have two usernames in our system (as shown in the error message). I can delete one of them and then your authentication should work properly. Which of those usernames would you like to keep?

**Comment by ZhuofuLi** [comment]
Can you please delete the username "zhuofu" for me? Thanks!

**Comment by rra** [comment]
Done. You should hopefully now be able to log in.

**Comment by ZhuofuLi** [comment]
It works now. Thanks!

**Comment by rra** [comment]
Closing as fixed. Sorry about the issues! Let us know if you have any further problems.
