### ISSUE TITLE
Stuck in Login Loop

### ISSUE THREAD

**Issue by mochaait** [rubin-dp0/Support#66]
One Bug Solved, One More Appears...

Hi, my next issue seems to be similar to some previous bugs with getting stuck at Comanage after going through CILogon. I attempted some of the fixes that others have tried, but the basic gist of the issue is that upon logging in through the RSP cloud site, I am met with a redirect to Comanage with the signup track showing:

<img width="1512" alt="Screenshot 2024-05-31 at 1 55 05 PM" src="https://github.com/rubin-dp0/Support/assets/157167291/30a9265d-3f6a-4798-b62d-a8eea067fca2">

After clicking begin, I'm met with:

<img width="1512" alt="Screenshot 2024-05-31 at 1 55 33 PM" src="https://github.com/rubin-dp0/Support/assets/157167291/45200450-feb2-41f6-af64-afe9913cefd8">

<img width="1512" alt="Screenshot 2024-05-31 at 1 59 27 PM" src="https://github.com/rubin-dp0/Support/assets/157167291/51e10bbc-991c-40bc-8178-f8cddaaaf118">

I figured some other login bugs had a similar issue, and after looking at one of the other fixed issues, I tried to recreate the steps that were laid out in an attempt to fix it. First, logging out of my account on the Comanage page:

<img width="1512" alt="Screenshot 2024-05-31 at 1 59 33 PM" src="https://github.com/rubin-dp0/Support/assets/157167291/f4d26e53-6356-4a6b-af1f-d25c5554c4f4">

Then, I went back out and into the Rubin Platform login page:

<img width="1512" alt="Screenshot 2024-05-31 at 1 58 55 PM" src="https://github.com/rubin-dp0/Support/assets/157167291/4aef8dcd-bc05-47e8-a6e8-a7c3eb0c87a9">

Interestingly, after doing the login once, it showed me the page once again. I tried clicking login, passed through...

<img width="1512" alt="Screenshot 2024-05-31 at 2 06 04 PM" src="https://github.com/rubin-dp0/Support/assets/157167291/d0ed1e62-a971-49fe-9cb2-c3ad12920f10">

...and ended up back where I started.

It's baffling that another issue has come up on my side, but any help would be much appreciated!

**Comment by MelissaGraham** [comment]
Hi @mochaait, I'm sorry you continue to encounter issues. As far as I can tell in the system, your account has been activated just fine. From the above, it seems like when you go to data.lsst.cloud and click log in, it is directing you to id.lsst.cloud.

Let's try this first. Make sure you're completely logged out of data.lsst.cloud and id.lsst.cloud, clear your cache, and restart your browser. Then go to data.lsst.cloud and instead of logging in, attempt to enter the Portal or Notebook aspects by clicking on one of the central panels (but _not_ the API panel). This should (as I understand it) prompt a log in that then takes you onwards into the RSP aspect you selected, and not to id.lsst.cloud.

**Comment by mochaait** [comment]
Hi @MelissaGraham, thanks for the responses.

So I tried as you suggested, clearing my cache again and restarting the browser. I then went through both the portal and notebook aspects to log in. Interestingly, both came up with the id.lsst.cloud redirect instead. 

Even more interestingly, is that when I redirected myself to data.lsst.cloud, I was not actually logged in on the site, despite having been logged in on the Comanage:

<img width="1512" alt="Screenshot 2024-05-31 at 2 55 28 PM" src="https://github.com/rubin-dp0/Support/assets/157167291/b2ed01b5-2572-4159-9a91-4798f8e0dff9">

<img width="1512" alt="Screenshot 2024-05-31 at 3 01 02 PM" src="https://github.com/rubin-dp0/Support/assets/157167291/3b699b76-3fec-4bad-9630-722f8d37828e">

This is an interesting point I thought might be part of the issue.

**Comment by MelissaGraham** [comment]
OK thanks for trying that @mochaait  -- we've reach the end of what I know about the system so I'll refer this to our RSP developers to get this login issue solved.

**Comment by frossie** [comment]
It looks like the user does not have a username selected. This could be, for example,  because the javascript was not allowed to run to completion during the sign-up process (or was prevented from running due to a browser setting). Given sign-up was never completed my recommendation is @MelissaGraham expunge the user and they try again, preferably with any browser plugins disabled or a different browse. If there are still problems after that let me know and we can try and record this process on a zoom call to see if we can spot why this is happening

**Comment by mochaait** [comment]
@frossie This could be the case-- as I had my Adblock plugin on when I did the initial signup. I'm down to try again with Adblock disabled.

**Comment by MelissaGraham** [comment]
@mochaait  When I saw [your Forum post](https://community.lsst.org/t/interpreting-color-color-diagrams-for-presumed-variable-stars/8657) I assumed you had gained RSP access. We should not expunge if you're using your account.

Confirm if you'd like your current account expunged so you can start over?

**Comment by mochaait** [comment]
@MelissaGraham Hi, yeah I'd like my account expunged. The data in that forum post was gathered with help from some collaborators.

**Comment by MelissaGraham** [comment]
@mochaait thank you for confirming, your account has been expunged. Apologies for the inconvenience here, and do let us know how the next attempt goes.

**Comment by mochaait** [comment]
Alright, perfect-- awaiting verification. I'll let you know if there are issues from there @MelissaGraham

**Comment by mochaait** [comment]
Yup, it seems to be working fine!

**Comment by MelissaGraham** [comment]
Wonderful news @mochaait, thank you for confirming! Closing this ticket as we've reached a successful resolution. Thanks too @frossie.
